import type { OptimizerSettings } from "./model";

export const DEFAULT_SETTINGS: OptimizerSettings = {
    timeToWaitBeforeSuspend: 1000,
    resize: "No Resize",
    textureMode: "webp",
    textureExportMode: "image",
    sceneExportMode: "glb",
    draco: false,
    dedup: true,
    prune: true,
    flatten: true,
    join: true,
    resample: true,
    sparse: true,
    sparseRatio: 0.333333,
    weld: true,
    weldTolerance: 0.001,
    weldToleranceNormal: 0.25,
    simplify: false,
    simplifyRatio: 0,
    simplifyError: 0.0001,
    simplifyLockBorder: false,
    reorder: false,
    quantize: false,
    meshopt: false,
    meshoptLevel: "high",
    gpuInstancing: false,
    qualityLevel: 155,
    compressionLevel: 2,
    supercompression: false,
    baseColorUASTC: false,
    normalUASTC: false,
    metallicUASTC: false,
    emissiveUASTC: false,
    occlusionUASTC: false,
};
